title: Creative
baseline: Start Bootstrap Theme
description: An attractive one page Bootstrap theme perfect for creative portfolios and businesses.
baseurl: /
assets:
  compile:
    variables:
      primary: '#F05F40' # default color, set here to be overridden in another context with an env. variable.
